# This is a basic workflow to help you get started with Actions

name: pr-to-alisis-air

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: alis-is/air

      - name: Reset the default branch with upstream changes
        run: |
          git remote add upstream https://github.com/jpaarhuis/air.git
          git fetch upstream master:upstream-master
          git reset --hard upstream-master

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          add-paths: |
            ami/definition/posmn/**/*